version: "2.1"

volumes:
  mybank-dependencies:
  mybank-builds:

services:
  mybank:
    build: ./Dockerfile
    command: mix phx.server
    volumes:
      - .:/usr/src/app
      - mybank-dependencies:/usr/src/app/deps
      - mybank-builds:/usr/src/app/_build
    ports:
    - "4000:4000"
